language: node_js
node_js:
  - 8
  - 10
env:
  - CI=true  
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm test
notifications:
  webhooks: https://dev.webspace.rocks/travis-discord/
before_install:
 - sudo apt-get install -qq lftp sshpass
deploy:
  provider: script
  script: sh deploy.sh
  skip_cleanup: true